### ISSUE TITLE
dependencies question

### ISSUE THREAD

**Issue by reminvestor** [Chillisoft/splunk4net#1]
Why are these required? I don't see them being used? 

System.Data.Sqlite.dll
x86/Sqlite.Interop.dll
x64/Sqlite.Interop.dll

**Comment by fluffynuts** [comment]
Hi

They are used for persistently buffering logs into a local sqlite database
before attempting to send them off to Splunk. The idea is to make loggimg
resilient against network failure, and to do so transparently to your
application. The intermediate database is automatically generated in an app
data folder (under %PROGRAMDATA% iirc) with a name created from a hash of
the application path.

You can disable buffering, in which case you may not need the interop dlls
as they are, iirc, loaded late, but I'm not sure about the .net assembly.
You could give it a go and see. With the option turned off, logs should
still be buffered in memory, but obviously if the network is down, buffered
logs wouldn't survive between application runs.

The first is the .net connector and you'd need one of the other two
depending on the architecture you've compiled for.

-d
