### ISSUE TITLE
Format Appenders not passing message

### ISSUE THREAD

**Issue by ghost** [Chillisoft/splunk4net#2]
When using InfoFormat (Or any of the Format appenders) the message comes up as blank.

The code used is below:

`ILog _logWriter = LogManager.GetLogger(typeof(Program));
XmlConfigurator.Configure();
string x = "Hello";
_logWriter.InfoFormat("{0} World!", x);
`

If I use just `_logWriter.Info("Hello World!");` it works fine.

**Comment by fluffynuts** [comment]
Hi

Apologies for the massive delay in getting back to you )':

I'd just like to let you know that this is on my radar and I'll check it out ASAP (:

You can work around this for the moment with string.Format or interpolated strings, but I understand that the library isn't doing what you expected -- I'll definitely be looking into this in more depth soon.

**Comment by ghost** [comment]
Thanks!

In my case I'm adding splunk support to an existing app, it gets the big stuff like the exception logging, mostly i'm just missing out on info and debug logging that I've also got going to a SQL Server.

**Comment by fluffynuts** [comment]
This is fixed in nuget package 1.0.10

As at time of writing, the package has not been indexed yet, so you may install with:

`install-package splunk4net -version 1.0.10`

Or wait until

`update-package splunk4net`

reports an update to 1.0.10.

Closing as resolved. Thanks for the report (:

**Comment by ghost** [comment]
Working great! Thanks
